// backup-react/src/layouts/main-layout.tsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import Header from './header';

const MainLayout = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-grow">
        <Header />
        <Outlet />
      </main>
    </div>
  );
};

export default MainLayout;

// src/app/layouts/main-layout/main-layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from '../header/header.component';

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent],
  templateUrl: './main-layout.component.html',
  styleUrl: './main-layout.component.css'
})
export class MainLayoutComponent {

}

<div class="d-flex flex-column min-vh-100">
  <main class="flex-grow-1">
    <app-header></app-header>
    <router-outlet></router-outlet>
  </main>
</div>
